name: ci-tests
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: python:3.8
    steps:
      - uses: actions/checkout@v2
      
      - name: ci_run
        run: |
          pip install -r requirements.txt
          pip install flake8
          pytest tests/
          flake8 .
